apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-url
  namespace: backend
data:
  querystring: "mongodb://your-mongo-db-url"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend
  labels:
    app: backend
    maintainer: vikas
spec:
  replicas: 3
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: backend-pod
  template:
    metadata:
      name: backend-pod
      labels:
        app: backend-pod
    spec:
      containers:
        - name: backend-pod
          image: vikasprince/incident-log-api:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: "MONGODB_URL"
              valueFrom:
                configMapKeyRef:
                  name: mongo-url
                  key: querystring
            - name: "PORT"
              value: 5000
      resources:
        limits:
          memory: "1Gi"
          cpu: "1"
        requests:
          memory: "500Mi"
          cpu: "0.5m"
      livenessProbe:
        httpGet:
          path: "/health"
          port: 5000
        initialDelaySeconds: 30
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: "/health"
          port: 5000
        initialDelaySeconds: 60
        periodSeconds: 5


---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: backend-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
